name: email-parser
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12
  - pip
  - openpyxl
  - pandas
  - pillow
  - pytest
  - pytest-cov
  - black
  - isort
  - mypy
  - pip:
      - email-validator
      - filetype
      - pypdf2
